// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jnkcyebdrxjqkjulbnow.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impua2N5ZWJkcnhqcWtqdWxibm93Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA2MTg3MzYsImV4cCI6MjA3NjE5NDczNn0.f22KSB668RUvHjj8_l_zA3zRBekV_Yhg7p8JvpP3H4I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});